{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.appName }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Values.appName }}-cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            command: {{ toJson .Values.cronjob.command }}
            args:
{{ toYaml .Values.cronjob.args | indent 12 }}
{{- end -}}