{{- if hasKey .Values "migrationCommand" -}}
{{- if .Values.migrationCommand.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}-migration-{{ randAlphaNum 6 | lower }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret }}
  containers:
  - name: {{ .Values.appName }}-migration
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: IfNotPresent
    command: {{ toJson .Values.migrationCommand.command }}
    args:
{{ toYaml .Values.migrationCommand.args | indent 6 }}
    env:
{{ toYaml .Values.environments | indent 6 }}
{{- end }}
{{- end }}
